org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

java_version=17

mod_version=1.0.0
display_version=1.0.0
maven_group=com.arthou
archives_base_name=arthous-invview-forge-1201
mod_id=invview
mod_name=Arthou's InvView
mod_license=All Rights Reserved
mod_authors=Arthou
mod_description=Inventory and ender chest viewer/editor for Forge 1.20.1.
